language: android
os: linux
dist: trusty
android:
  components:
    - build-tools-29.0.3
    - android-29
    - tools
before_install:
  - cd $TRAVIS_BUILD_DIR/
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;30.0.2"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - cd $TRAVIS_BUILD_DIR/
  - chmod +x gradlew
  - "./gradlew testDebugUnitTest assembleDebug"