name: Android CI (release)

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  apk:
    name: Build release APK (and upload)
    if: "contains(github.event.head_commit.message, '📦')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: 🔧 Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: 🔑 Decode google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES > app/google-services.json
      - name: 📦 Build release APK
        run: bash ./gradlew assembleRelease
      - name: 🚀 Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 7
